0330/workshop0330/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
]

0330/workshop0330/either/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('games/', include('games.urls')),
    path('accounts/', include('accounts.urls')),
]

0330/workshop0330/games/urls.py
from django.urls import path
from . import views


app_name = 'games'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:game_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:pk>/choice/<str:pick>/',views.choice, name='choice')
    

]

0330/workshop0330/games/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Game(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    left_side = models.TextField()
    right_side = models.TextField()

    left_number = models.IntegerField(default=0)
    right_number = models.IntegerField(default=0)


class Comment(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

class Choice(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    pick = models.BooleanField()

0330/workshop0330/games/forms.py
from django import forms
from .models import Game, Comment


class GameForm(forms.ModelForm):
    title = forms.CharField(
        label='제목',
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'rows': 5,
                'cols': 20,
            }
        )
    )
    left_side = forms.CharField(
        label = '선택1',
        widget = forms.TextInput(
            attrs={
                'class': 'form-control',
               
            }
        )
    )
    right_side = forms.CharField(
        label = '선택2',
        widget = forms.TextInput(
            attrs={
                'class': 'form-control',
                
                
            }
        )
    )


    class Meta:
        model = Game
        fields = '__all__'
        exclude = ('user','left_number','right_number')


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        # fields = '__all__'
        exclude = ('game', 'user',)
        

0330/workshop0330/games/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_safe, require_http_methods, require_POST
from django.http import HttpResponse, HttpResponseForbidden
from .models import Game, Comment
from .forms import GameForm, CommentForm
import random


# Create your views here.

def index(request):
    
    games = Game.objects.order_by('-pk')
    form = GameForm()
    context = {
        'form': form,
        'games' : games,
    }
    return render(request, 'games/index.html', context)

@login_required
@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = GameForm(request.POST)
        if form.is_valid():
            game = form.save(commit=False)
            game.user = request.user
            game.save()
            return redirect('games:detail', game.pk)
    else:
        form = GameForm()
    context = {
        'form': form,
    }
    return render(request, 'games/create.html', context)



def detail(request, pk):
    game = get_object_or_404(Game, pk=pk)

    if game.left_number == 0 and game.right_number == 0:
        left = 0
        right = 0
    else:
        left = round(game.left_number / (game.left_number + game.right_number) * 100, 2)

        right = round(game.right_number / (game.left_number + game.right_number) * 100, 2)
    
    comment_form = CommentForm()
    comments = game.comment_set.all()
    context = {
        'game': game,
        'comment_form': comment_form,
        'comments': comments,
        'left' : left,
        'right': right,
    }
    return render(request, 'games/detail.html', context)

@require_POST
def choice(request, pk, pick):

    game = Game.objects.get(pk=pk)
    if pick =='left_side':
        game.left_number += 1
        game.save()
    elif pick == 'right_side':
        game.right_number += 1
        game.save()
    return redirect('games:detail', pk)

@require_POST
def delete(request, pk):
    game = get_object_or_404(Game, pk=pk)
    if request.user.is_authenticated:
        if request.user == game.user:
            game.delete()
            return redirect('games:index')
    return redirect('games:detail', game.pk)


@login_required
@require_http_methods(['GET', 'POST'])
def update(request, pk):
    game = get_object_or_404(Game, pk=pk)
    if request.user == game.user:
        if request.method == 'POST':
            form = GameForm(request.POST, instance=game)
            if form.is_valid():
                form.save()
                return redirect('games:detail', game.pk)
        else:
            form = GameForm(instance=game)
    else:
        return redirect('games:index')
        # return HttpResponseForbidden()
    context = {
        'form': form,
        'game': game,
    }
    return render(request, 'games/update.html', context)
        

@require_POST
def comments_create(request, pk):
    if request.user.is_authenticated:
        game = get_object_or_404(Game, pk=pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.game = game
            comment.user = request.user
            comment.save()
            return redirect('games:detail', game.pk)
        context = {
            'comment_form': comment_form,
            'game': game,
        }
        return render(request, 'games/detail.html', context)
    return redirect('accounts:login')
    # return HttpResponse(status=401)


@require_POST
def comments_delete(request, game_pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
        # return HttpResponseForbidden()
    return redirect('games:detail', game_pk)
    # return HttpResponse(status=401)

0330/workshop0330/games/templates/games/create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1>CREATE</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit">
  </form>
  <hr>
  <a href="{% url 'games:index' %}">[back]</a>
{% endblock %}

0330/workshop0330/games/templates/games/detail.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}
  <h2>DETAIL</h2>
  <p><b>작성자 : {{ game.user }}</b></p>
  <h3>{{ game.title }}</h3>

  <form action="{% url 'games:choice' game.pk "left_side" %}" method="POST">
    {% csrf_token %}
    <p>글 번호 : {{ game.pk }}</p>
    <p>선택1</p>
    <button>{{ game.left_side }}</button>
    <p>통계:  {{ game.left_number }}명, {{ left }}%</p>
  </form>
  <form action="{% url 'games:choice' game.pk "right_side" %}" method="POST">
    {% csrf_token %}
    <p>선택2</p>
    <button>{{ game.right_side }}</button>
    <p>통계:  {{ game.right_number }}명, {{ right }}%</p>
    <a href="{% url 'games:detail' game.pk %}">[DETAIL]</a>
    <hr>
  </form>
  <hr>
  {% if request.user == game.user %}
    <a href="{% url 'games:update' game.pk %}" class="btn btn-primary">[UPDATE]</a>
    <form action="{% url 'games:delete' game.pk %}" method="POST">
      {% csrf_token %}
      <button class="btn btn-danger">DELETE</button>
    </form>
  {% endif %}
  <a href="{% url 'games:index' %}">[back]</a>
  <hr>
  <h4>댓글 목록</h4>
  <p>{{ comments|length }}개의 댓글이 있습니다.</p>
  <ul>
    {% for comment in comments %}
      <li>
        {{ comment.user }} - {{ comment.content }}
        {% if request.user == comment.user %}
          <form action="{% url 'games:comments_delete' game.pk comment.pk %}" method="POST" class="d-inline">
            {% csrf_token %}
            <input type="submit" value="DELETE">
          </form>
        {% endif %}
      </li>
    {% empty %}
      <p>아직 댓글이 없네요...</p>
    {% endfor %}
  </ul>
  <hr>
  {% if request.user.is_authenticated %}
    <form action="{% url 'games:comments_create' game.pk %}" method="POST">
      {% csrf_token %}
      {{ comment_form }}
      <input type="submit">
    </form>
  {% else %}
    <a href="{% url 'accounts:login' %}">[댓글을 작성하려면 로그인 하세요.]</a>
  {% endif %}
{% endblock %}
  

0330/workshop0330/games/templates/games/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>Games</h1>
  {% if request.user.is_authenticated %}
    <a href="{% url 'games:create' %}">[CREATE]</a>
  {% else %}
    <a href="{% url 'accounts:login' %}">[새 글을 작성하려면 로그인하세요.]</a>
  {% endif %}
  <hr>
  <p><b>누르시면 자동으로 이동합니다.</b></p>
  <hr>
  {% for game in games %}
    <form action="{% url 'games:choice' game.pk "left_side" %}" method="POST">
      {% csrf_token %}
      <p><b>작성자 : {{ game.user }}</b></p>
      <p>글 번호 : {{ game.pk }}</p>
      <h3>{{ game.title }}</h3>
      <button>{{ game.left_side }}</button>
      <button>{{ game.right_side }}</button>
    </form>
    <br>
    <a href="{% url 'games:detail' game.pk %}">[DETAIL]</a>
    <hr>
  {% endfor %}
  <hr>
  

{% endblock %}

0330/workshop0330/games/templates/games/update.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1>UPDATE</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit">
  </form>
  <hr>
  <a href="{% url 'games:index' %}">[back]</a>
{% endblock %}