0310/crud/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('detail/', views.detail, name='detail')

]

0310/crud/articles/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=30)  # 필수 인자 존재 (문자열 길이 제한)
    content = models.TextField()

    def __str__(self):
        return self.title
    

0310/crud/articles/views.py
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.
def index(request):

    articles = Article.objects.all()

    context = {
        'articles' : articles,
    }

    return render(request, 'articles/index.html', context)

def new(request):
    return render(request, 'articles/new.html')

def create(request):
    if request.method == "POST":
        articles = Article()

        articles.title = request.POST.get('title')
        articles.content = request.POST.get('content')

        articles.save()

    return redirect('articles:index')

def detail(request):
    return render(request, 'articles/detail.html')

0310/crud/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
<h1>개발중</h1>
{% endblock  %}

0310/crud/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}

  <h1>INDEX</h1>
  
  <a href="{% url 'articles:new' %}">NEW</a>
  <br>
  
  {% for article in articles %}
  <br>
  <h2>제목: {{ article.title}}</h2>
  <p>내용: {{ article.content }}</p>
  <a href="{% url 'articles:detail' %}">DETAIL</a>
  <br>
  <br>
  {% endfor %}

  {% comment %} {{ articles.title }} {% endcomment %}
{% endblock  %}

0310/crud/articles/templates/articles/new.html
{% extends 'base.html' %}

{% block content %}
  <h1>NEW</h1>

  <form action="{% url 'articles:create' %}" method="POST">
    {% csrf_token %}
    <label for="title">TITLE:</label>
    <input type="text" id="title" name="title"><br>
    <label for="content">CONTENT:</label>
    <textarea name="content" id="content" cols="30" rows="10"></textarea><br>
    <input type="submit" value="작성">
  
  </form>

  <a href="{% url 'articles:index' %}">BACK</a>
  

{% endblock  %}