0311/crud/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),

]

0311/crud/articles/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=30)  # 필수 인자 존재 (문자열 길이 제한)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    

0311/crud/articles/views.py
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.
def index(request):

    articles = Article.objects.all()

    context = {
        'articles' : articles,
    }

    return render(request, 'articles/index.html', context)

def new(request):
    return render(request, 'articles/new.html')

def create(request):
    if request.method == "POST":
        articles = Article()

        articles.title = request.POST.get('title')
        articles.content = request.POST.get('content')

        articles.save()

    return redirect('articles:detail', articles.pk)

def detail(request, pk):
    article = Article.objects.get(pk=pk)
    
    context = {
        'article' : article,
    }
    return render(request, 'articles/detail.html', context)

def edit(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article': article,
    }
    return render(request, 'articles/edit.html', context)

def update(request, pk):

    article = Article.objects.get(pk=pk)

    article.title = request.POST.get('title')
    article.content = request.POST.get('content')

    article.save()

    return redirect('articles:detail', article.pk)

def delete(request, pk):

    article = Article.objects.get(pk=pk)

    article.delete()

    return redirect('articles:index')

    

0311/crud/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
<h1>DETAIL</h1>
<hr>
<h2>{{ article.title }}</h2>
<p>{{ article.content }}</p>
<p>작성일: {{ article.created_at }}</p>
<p>수정일:{{ article.updated_at }}</p>

<a href="{% url 'articles:edit' article.pk %}">EDIT</a>
<a href="{% url 'articles:delete' article.pk %}">DELETE</a>
<br>

<a href="{% url 'articles:index' %}">BACK</a>
{% endblock  %}

0311/crud/articles/templates/articles/edit.html
{% extends 'base.html' %}

{% block content %}
<h1>EDIT</h1>
<form action="{% url 'articles:update' article.pk %}" method="POST">
    {% csrf_token %}
    <label for="title">TITLE</label>
    <input type="text" id="title" name="title" value="{{ article.title }}"><br>
    <label for="content">CONTENT </label>
    <textarea name="content" id="content" cols="30" rows="10">{{ article.content }}</textarea><br>
    <input type="submit" value="수정">
</form>

<a href="{% url 'articles:index' %}">BACK</a>

{% endblock  %}

0311/crud/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}

  <h1>INDEX</h1>
  
  <a href="{% url 'articles:new' %}">NEW</a>
  <br>
  
  {% for article in articles %}
  <br>
  <h2>제목: {{ article.title}}</h2>
  <p>내용: {{ article.content }}</p>
  <a href="{% url 'articles:detail' article.pk %}">DETAIL</a>
  <br>
  <br>
  {% endfor %}

  
{% endblock  %}

0311/crud/articles/templates/articles/new.html
{% extends 'base.html' %}

{% block content %}
  <h1>NEW</h1>

  <form action="{% url 'articles:create' %}" method="POST">
    {% csrf_token %}
    <label for="title">TITLE:</label>
    <input type="text" id="title" name="title"><br>
    <label for="content">CONTENT:</label>
    <textarea name="content" id="content" cols="30" rows="10"></textarea><br>
    <input type="submit" value="작성">
  
  </form>

  <a href="{% url 'articles:index' %}">BACK</a>
  

{% endblock  %}